=begin
#Togai Apis

#APIs for Togai App

The version of the OpenAPI document: 1.0
Contact: engg@togai.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.1.0

=end

require 'date'
require 'time'

module TogaiClient
  class MetricName
    EVENTS = "EVENTS".freeze
    USAGE = "USAGE".freeze
    REVENUE = "REVENUE".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = MetricName.constants.select { |c| MetricName::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #MetricName" if constantValues.empty?
      value
    end
  end
end
