=begin
#Togai Apis

#APIs for Togai App

The version of the OpenAPI document: 1.0
Contact: engg@togai.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.1.0

=end

require 'date'
require 'time'

module TogaiClient
  class PricingModel
    TIERED = "TIERED".freeze
    VOLUME = "VOLUME".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = PricingModel.constants.select { |c| PricingModel::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #PricingModel" if constantValues.empty?
      value
    end
  end
end
